### ISSUE TITLE
Sonar sensor - pulse width

### ISSUE THREAD

**Issue by bobwolff68** [FRCTeam1967/FRCTeam1967#7]
Test out sonar sensor using pulse width output

**Comment by meghatron3000** [comment]
The sonar sensor that we are using to replace the light sensor comes with its own circuit.

**Comment by bobwolff68** [comment]
Are you saying that the sonar's feedback comes over the PWM bus as an input?
- I wasn't aware this was possible. Could be?
- If it really is over PWM, please be careful as there are only 10 PWM ports and I think I heard mechanical folks say they would likely use 8 or possibly even 9 of these.
- There may be more  PWM ports available via the expansion ports in the center, but this would require some investigation.
