### ISSUE TITLE
Sonar sensor - analog

### ISSUE THREAD

**Issue by bobwolff68** [FRCTeam1967/FRCTeam1967#8]
Program the sonar sensor using the analog output

**Comment by bobwolff68** [comment]
jankyLightSensor class seems in order here so that the details are hidden about how it happens but that from the outside there's just a "Get()" function that returns true or false to determine if it's open or closed.

**Comment by meghatron3000** [comment]
We have decided against light sensors because we found a way to make the sonar sensors accurate

**Comment by bobwolff68** [comment]
Have the sonar sensors been fully tested? What/Where are the results?

**Comment by gillz181967** [comment]
We didn't end up using sonar sensors :)
