### ISSUE TITLE
Program the camera via code - not just via config website

### ISSUE THREAD

**Issue by bobwolff68** [FRCTeam1967/FRCTeam1967#9]
Camera folks - write a small test program which programs the camera to have preferred resolution, framerate, and quality. Then test by resetting camera to defaults and see the program make its changes automatically.

**Comment by gillz181967** [comment]
I don't think we really need to code it to be the preferred settings. You'd have to hold the reset button for quite a long time, and it doesn't take too long to redo the settings IF it just so happened to reset.

**Comment by bobwolff68** [comment]
I would agree with you that the risk is relatively low and it doesn't take a long time to fix. _However_, sometimes it is not clear that something is broken until troubleshooting has taken place and this can take a long time. If it can be made "correct" automagically by programming, then even if it did 'break', the programming will set those settings appropriately regardless of troubles. This is a self-fixing / self-healing situation. A beautiful thing in my book. :) I will let you and your team lead @meghatron3000 make a decision about an action here.
